### ISSUE TITLE
Support for Begin project root to be a sub-directory of a repo

### ISSUE THREAD

**Issue by Stegosource** [smallwins/begin-issues#17]
My current project was started with the Vue CLI. It's primarily a frontend focused app. I wanted to add some backend functionality via serverless functions, but the majority of the work is front end. 

With all that said, I'd like to keep my project root oriented towards this frontend project. But Begin relies on the root being oriented towards the Begin project. If there was a setting to define a subdirectory, then we could use that subdirectory for the Begin files. This could exist within the `.arc` file, or maybe in the Begin dashboard (and a CLI flag for local).

An example project could look like:
```
package.json (frontend)
/src (frontend)
--index.html
/backend (Begin code)
--.arc
--package.json
--/src
----/http
------get-posts.js
```

Note that with this setup, I'm using Netlify to handle build/deploy the frontend. I would want Begin to handle the backend. And I'd like the code to exist in the same repo.

**Comment by kristoferjoseph** [comment]
Thanks for taking the time to file this issue.

We do our best to balance enhancement requests with the ongoing development of the platform.
In the meantime, there are a few workarounds you can try if this is blocking you.

1. Move your frontend resources into a sub-directory.
2. Make two repositories; one for your API and one for your frontend.
3. Use the [Begin Vue example app](https://github.com/begin-examples/node-vue) which has both frontend and an example API already set up for you.

**Comment by Stegosource** [comment]
Thanks @kristoferjoseph. I totally understand that this is not a top priority, but I do think it's worth having in the backlog somewhere. Im sure I'm not the only one.

In the meantime, I will move the frontent code. I took a look at the Vue example, but I dont think that will work for me. It's basically how I have things setup now and is not working.

**Comment by kristoferjoseph** [comment]
Definitely.
I maintain the Vue Example app so if you find a limitation using it I will always do my best to get it working for you.
