### ISSUE TITLE
[begin-functions-app] Add option to run local "server" on a different port

### ISSUE THREAD

**Issue by kmelve** [smallwins/begin-issues#2]
**Is your feature request related to a problem? Please describe.**
When developing serverless services, it's often the case that you're running multiple local servers. Since port 3333 is a common default, it should be possible to run the begin-functions-app on a different server.

**Describe the solution you'd like**
There are multiple ways of solving this. The app can offer to start on an alternative port if the one it tries is occupied. I believe create-react-app does this. It should also be possible to manually set the port by either exporting an environment variable (PORT=4444; npm start), or preferably passing it in as a flag: `npm start -- --port=4444`. 

**Additional context or notes**
I see that there is a `// TODO make port configurable` in the @architect/workflows/sandbox/http. So I guess this is on the roadmap – consider this a +1 on that todo.

**Comment by ryanblock** [comment]
Ref: https://github.com/arc-repos/arc-workflows/issues/92

Will reflect back any interesting developments here.

Ofc, obligatory "PRs welcome!" 🌈

**Comment by ryanblock** [comment]
Right on, @kmelve, thanks!

Just a heads up: @brianleroux (aka bdfl) is out the next couple days for his birthday (happy birthday, Brian!), so we'll review when he's back next week. Thanks for your patience!

**Comment by ryanblock** [comment]
Nice, looks like folks were able to get to it last night, now published to `3.1.16`. Ty @brianleroux + @austinkelleher!
