### ISSUE TITLE
Bug with table names

### ISSUE THREAD

**Issue by Stegosource** [smallwins/begin-issues#20]
**Describe the issue**

Having a weird issue where adding two different entries to two different tables somehow puts the two entries into one table. But if I change the table names, it works as expected. 

**Steps to reproduce**
1. set variables:
```
const USER_TABLE = "tempuser
cosnt USERNAME_TABLE =  "tempusername",
```
2. Save entries in different tables:
```
const createUser = data.set({
  table: USER_TABLE,
  key: accountId,
})
const storeUsername = data.set({
  table: USERNAME_TABLE,
  key: username,
})
```
3. Check users table:
```
const users = await data.get({ table: USER_TABLE })
console.log("users", users)
```
4. See the response is an array with 2 entries instead of 1.
5. Stop and start server
6. Change variables:
```
const USER_TABLE = "usertemp",
cosnt USERNAME_TABLE =  "usernametemp",
```
7. Rerun step 2 & 3
8. See the response is an array with 1 entry.

**Expected behavior**
Expected behavior is like step 7.

**Comment by brianleroux** [comment]
this is a bug! thx for the repro steps it really helped. just building a fix bbiab 🙏

**Comment by brianleroux** [comment]
eh sorry for the auto-close / the latest version of begin/data should be published in a few moments and should fix this behavior ! thank u again for reporting 💯

**Comment by Stegosource** [comment]
Word. No worries. Glad to help.

**Comment by Stegosource** [comment]
By the way, @brianleroux any idea on what the actual cause of the bug is? I originally thought maybe the use of forbidden characters, but by the end, there were issues with just letters, so that couldnt be it.

**Comment by brianleroux** [comment]
it was a bug with how we store the table name in dynamodb. because both tables had the same leading characters it was accidentally including both records in the lookup!

**Comment by Stegosource** [comment]
Word. 

Hey, somewhat unrelated question, but do you employ a single-table DB pattern generally or store data in multiple DBs?

**Comment by ryanblock** [comment]
In Begin Data we use a single table, however for more advanced uses we use and suggest multiple tables and GSIs. begin.com has >10 tables, for example.

**Comment by brianleroux** [comment]
its a great question and the answer is nuanced. just responded to similar here https://github.com/architect/arc.codes/issues/193#issuecomment-616682718

**Comment by Stegosource** [comment]
Yeah thanks. That thread does reveal a lot. Im used to SQL, so the whole single-table thing is a paradigm shift. Makes sense, but hard to approach, and requires solid knowledge of the access patterns. Im using Begin for a brand new project, and not sure what that looks like, so it's a bit weird to tackle that. I also need to figure out more about the primary key and sort key implementation in Begin.
