### ISSUE TITLE
[website] Broken link: Open function in GitHub

### ISSUE THREAD

**Issue by kmelve** [smallwins/begin-issues#5]
**Expected behavior**
The “Open function in GitHub” should open the function in GitHub (and not 404).

**Description of bug**

![2018-08-10 at 07 24](https://user-images.githubusercontent.com/1131579/43940252-0e68f9a8-9c6f-11e8-920c-1f3347b62001.png)

**Comment by ryanblock** [comment]
Good find, thanks! Just patched.
