### ISSUE TITLE
Stuck at the "Setting up and provisioning..." screen

### ISSUE THREAD

**Issue by ocean** [smallwins/begin-issues#7]
**Expected behavior**
My starter GitHub repo would be created and the staging version of the starter app would be deployed to Lambda.

**Description of bug**
The Begin profile starter app screen is stuck at "Setting up git repo and provisioning app…" with a spinner, it's making fetch requests in the background but has been stuck for 12 hours or more.

The GitHub `begin-functions-app` repo has not been created, and the Production and Staging Begin app URLs have been generated, but return an "Internal server error."

**Steps to reproduce**
Detailed steps to reproduce the behavior:
1. Sign up with Begin
2. Authorise account through GitHub OAuth flow
3. Go back to Begin "apps" page
4. See spinner moving but no app or repo created.

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 68

**Additional context or notes**
I have GitHub Two-factor Authentication enabled using an Authenticator app, could this have interfered with the API request your app made for permissions to my account??

**Comment by ryanblock** [comment]
Huh, that's a bummer. This process should take less than 30 seconds, so if it didn't something is definitely immediately wrong.

First up, please try this:
1. Settings → `Delete app`
2. https://begin.com/logout
3. Log back in and hit `Create app`

If that still isn't working, let me know! I'll be looking through our logs about this in the mean time.

> I have GitHub Two-factor Authentication enabled using an Authenticator app, could this have interfered with the API request your app made for permissions to my account??

It shouldn't have, no. GH Oauth tokens don't require a second factor.

**Comment by ocean** [comment]
Thanks Ryan, no worries, it's easy enough for little blips to occur, and I feel special that it's only happened to me so far  😀 

I'll have a go at signing up again now and see what happens.

**Comment by ocean** [comment]
Super nice, all working now, and the onboarding is great  👍

**Comment by ryanblock** [comment]
Nice, glad that worked!

So the errors we saw in our logs were related to bad credentials, which had me wondering whether you had possibly revoked Begin's Oauth token at any point before?

I'm guessing if that had occurred to you you would have already mentioned it, but just to be sure I'm asking – we have a known corner case auth issue that is known to fail silently, but it's super hard to reproduce, so I suspect it wasn't the case here.

**Comment by ocean** [comment]
I had revoked the Begin token once before - I signed up, then a couple of weeks later wondered what it was in my Git settings, so I revoked it. But then I'm pretty sure I re-authorised it first when I signed in the other day, after receiving the invite  🤷‍♂️  Hmm.
