### ISSUE TITLE
Local changes to `.arc` manifest not reflected in Begin UI

### ISSUE THREAD

**Issue by joshgillies** [smallwins/begin-issues#8]
**Is your feature request related to a problem? Please describe.**

Note I'm not sure if this is a bug or a missing feature.

Either way, here's my experience. After going though the setup of my first Begin app (really great on-boarding experience btw!) I cloned the app locally and started making some edits. The first was to add a new route. After running `ARC_LOCAL=1 npx create` I validated the new route was working by running `npm start`. All looked good. I then pushing the updated code to GitHub and which triggered a new build, upon completion I tried to access the new route via the staging URL, and got the following output: `{"message":"Missing Authentication Token"}`.

It seems as though these local modifications aren't picked up by the Begin app, and thus the app didn't get the new updates.

After manually adding the previously defined route through the Begin UI the new route worked as expected. Though the files created from `ARC_LOCAL=1 npx create` and my local modifications were overridden. See this commit: https://github.com/joshgillies/begin-functions-app/commit/d91ea1852bc598350233d811516492be1832e624

**Describe the solution you'd like**

Ideally the `.arc` manifest is automatically reflected in the Being UI and is automatically provisioned with a resulting build.

**Describe alternatives you've considered**

The alternative is to manage all newly defined routes from within the web UI.

**Additional context or notes**

N/A

**Comment by ryanblock** [comment]
Hey @joshgillies, thanks for this!

Fwiw as a workaround, I believe you should be able to create the route in the Begin interface and it should pick up and deploy the functions you already committed. (Please let me know if that didn't work!)

So we've talked about this internally for a while, and I'm going to move this over to our [feature request roadmap](https://begin.canny.io/), but before I do, wanted to get your thoughts. Would you prefer:

- Modifying the local arc file and having that modify the Begin app infra upon commit? or
- Having a simple Begin CLI tools for doing this, and not managing the arc manifest at all? i.e. `begin create get /test`, which would spin up the infra, set up the boilerplate function in git, etc.?
- (Both?)

**Comment by joshgillies** [comment]
Thanks @ryanblock and @brianleroux for the replies. Yes I'd agree both features would be a really good addition to the platform. 👍

**Comment by brianleroux** [comment]
heh, this is ooooold and good news! you can now edit your arc file and see changes reflected https://github.com/brianleroux/arc-example-progressive-bundle
